### ISSUE TITLE
Regarding custom datasets

### ISSUE THREAD

**Issue by adg-git** [facebookresearch/SEAL_OGB#12]
Please could you elaborate more on what you mean by "Using custom datasets is also easy by replacing the Planetoid dataset with your own". Do we need to convert our data (e.g. USAir) to torch_geometric.datasets?  Thanks.

**Comment by muhanzhang** [comment]
You need to write a pytorch_geometric dataset class (e.g., by inheriting [InMemoryDataset](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html?highlight=InMemoryDataset#torch_geometric.data.InMemoryDataset)) which contains a `data` object (your network in torch_geometric format, see this [example](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#data-handling-of-graphs)). Then, you can replace this [line](https://github.com/facebookresearch/SEAL_OGB/blob/db81b1bb648f83e164411b977e6f52452193e125/seal_link_pred.py#L397) with a call to your own dataset and run SEAL on it.

**Comment by adg-git** [comment]
Thanks. Also, please could you throw some light on the error below while running the code with the data object in the example link above,

Traceback (most recent call last):
  File "seal_link_pred.py", line 406, in <module>
    split_edge = do_edge_split(dataset)
  File "~/SEAL_OGB/utils.py", line 190, in do_edge_split
    data = dataset[0]
  File "~/torch_geometric/data/dataset.py", line 188, in __getitem__
    data = data if self.transform is None else self.transform(data)
TypeError: 'str' object is not callable

**Comment by muhanzhang** [comment]
Please check whether your self.transform is defined as a str instead of callable function. If you don't need to transform the data, you can set it to None.

**Comment by adg-git** [comment]
Thanks, I was able to create the data object but I am getting the following new error now
----------------------
File "seal_link_pred.py", line 87, in process
    pos_list = extract_enclosing_subgraphs(
  File "~/SEAL_OGB/utils.py", line 180, in extract_enclosing_subgraphs
    tmp = k_hop_subgraph(src, dst, num_hops, A, ratio_per_hop,
  File "~/SEAL_OGB/utils.py", line 45, in k_hop_subgraph
    fringe = neighbors(fringe, A)
  File "~/SEAL_OGB/utils.py", line 28, in neighbors
    res = set(A[list(fringe)].indices)
  File "~/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "~/scipy/sparse/_index.py", line 138, in _validate_indices
    row = self._asindices(row, M)
  File "~/scipy/sparse/_index.py", line 170, in _asindices
    raise IndexError('index (%d) out of range' % max_indx)
IndexError: index (20623) out of range
----------------------

original data.num_nodes=20628
but after this step>   data.edge_index = split_edge['train']['edge'].t()
data.num_nodes=20619

Could you point to what could be going wrong here.

**Comment by adg-git** [comment]
Also can we add edge weight by modifying
data.edge_attr: Edge feature matrix with shape [num_edges, num_edge_features] ?

And to make the network directed we need to set directed=True for SEALDataset?

**Comment by muhanzhang** [comment]
You need to set `data.num_nodes` at the time when you create `data`. Then everything will be consistent. 

You can directly add a field `edge_weight` to your `data` storing an N * 1 matrix of edge weights. This way, some GNNs will be able to use edge weights to control their message passing. If you add edge weights into edge_attr, they will be treated as normal edge features.

To make the network directed, you should create your network's edge_index in a non-symmetric way ([i,j] in edge_index does not necessarily mean [j,i] also in edge_index), and then set `directed = True`.

**Comment by adg-git** [comment]
Thanks for the above pointers. I have also added a feature request for only_predict as a separate issue.

**Comment by muhanzhang** [comment]
The `edge_weight` is created [here](https://github.com/facebookresearch/SEAL_OGB/blob/db81b1bb648f83e164411b977e6f52452193e125/seal_link_pred.py#L70) by counting duplicate edges between the same pair of nodes by default. If there are no duplicate edges, `edge_weight` will be made an N*1 all-one matrix. You can replace it by your own edge weight here. Then the subgraph extraction will be performed on the weighted adjcency matrix `A`.

**Comment by adg-git** [comment]
Just to confirm, drnl_node_labeling ignores direction of edges and edge weights for a weighted and directed subgraph?

**Comment by muhanzhang** [comment]
Yes.
