### ISSUE TITLE
 dataset = PygLinkPropPredDataset(name=args.dataset)

### ISSUE THREAD

**Issue by qiniubaguai** [facebookresearch/SEAL_OGB#40]
你好，张教授，我想问一下我的代码一开始运行出现这个报错是什么原因呀
Processing...
Traceback (most recent call last):
  File "D:\Pycharm_poject\GitHub_SEAL_OGB-main\seal_link_pred.py", line 420, in <module>
    dataset = PygLinkPropPredDataset(name=args.dataset)
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\ogb\linkproppred\dataset_pyg.py", line 64, in __init__
    super(PygLinkPropPredDataset, self).__init__(self.root, transform, pre_transform)
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 56, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\torch_geometric\data\dataset.py", line 87, in __init__
    self._process()
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\torch_geometric\data\dataset.py", line 170, in _process
    self.process()
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\ogb\linkproppred\dataset_pyg.py", line 124, in process
    additional_node_files = self.meta_info['additional node files'].split(',')
AttributeError: 'float' object has no attribute 'split'

**Comment by muhanzhang** [comment]
What dataset did you use? Based on the information, you can print out the `self.meta_info` of your in_memory_dataset to see why the value corresponding to `"additional node files"` is float instead of str.

**Comment by qiniubaguai** [comment]
您好 张教授
我使用的是代码自带的数据集 ogbl-collab 
我使用print输出结果为
D:\Program_Data\Anaconda3\envs\pytorch13\python.exe D:\Pycharm_poject\GitHub_SEAL_OGB-main\seal_link_pred.py 
Results will be saved in results/ogbl-collab_20230605203934
Command line input: python D:\Pycharm_poject\GitHub_SEAL_OGB-main\seal_link_pred.py
 is saved.
ogbl-collab
<class 'str'>
Processing...
Traceback (most recent call last):
  File "D:\Pycharm_poject\GitHub_SEAL_OGB-main\seal_link_pred.py", line 420, in <module>
    dataset = PygLinkPropPredDataset(name=args.dataset)
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\ogb\linkproppred\dataset_pyg.py", line 64, in __init__
    super(PygLinkPropPredDataset, self).__init__(self.root, transform, pre_transform)
  File "D:\Program_Data\Anaconda3\envs\pytorch13\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 56, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)

**Comment by Xi-yuanWang** [comment]
@qiniubaguai  Hello, updating ogb may solve this problem. See [https://github.com/snap-stanford/ogb/issues/423](url)
