### ISSUE TITLE
Running Issues of citation dataset

### ISSUE THREAD

**Issue by VeritasYin** [facebookresearch/SEAL_OGB#6]
Hi,

I'm using the default settings to run the model on the citation dataset. I tried twice but each time the code got stuck after the first run. The log is attached below

`Results will be saved in results/ogbl-citation_20201224232705
Command line input: python seal_link_pred.py --dataset ogbl-citation --num_hops 1 --use_feature --use_edge_weight --eval_steps 1 --epochs 10 --dynamic_train --dynamic_val --dynamic_test --train_percent 2 --val_percent 1 --test_percent 1
 is saved.
Total number of parameters is 260802
SortPooling k is set to 115
100%|███████████████████████████| 37985/37985 [34:46<00:00, 18.20it/s]
100%|███████████████████████████| 27059/27059 [23:07<00:00, 19.50it/s]
100%|███████████████████████████| 27059/27059 [23:08<00:00, 19.49it/s]
/home/***/anaconda3/envs/dlg_env/lib/python3.8/site-packages/ogb/linkproppred/evaluate.py:235: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729009598/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  ranking_list = (argsort == 0).nonzero()
MRR
Run: 01, Epoch: 01, Loss: 0.0910, Valid: 87.25%, Test: 84.76%
  0%|                            | 1/37985 [00:01<19:04:56,  1.81s/it]`

It simply stops over there, no crash or exit.

**Comment by muhanzhang** [comment]
Hello! I haven't seen this error before. It seems to be related to the deprecation of "nonzero()" in torch. OGB's master branch has recently fixed it, see [here](https://github.com/snap-stanford/ogb/commit/9076d52c366523b917cabf4d3744963e475ceedd). But it hasn't released it in a package. I would recommend you wait for the latest OGB 1.2.4. It not only fixes this warning, but also deprecates ogbl-citation by introducing ogbl-citation2. See this update: https://ogb.stanford.edu/docs/update/

**Comment by VeritasYin** [comment]
Hi, I have updated to the lastest OGB. But I still got the issue that the code got stuck at the begining of some epoch. Based on the log, it could be trigged by the dataloader queue since it showed there is a timeout warning.

**Comment by VeritasYin** [comment]
GPU training with the config of server: RAM 1.96T; CPU 4*AMD EPYC 7742 64-Core Processor; GPU Quadro RTX 8000

**Comment by muhanzhang** [comment]
Can you successfully run on other datasets? Is the code runnable on a intel-based server? I also wonder whether it's because of a multiprocessing issue of AMD. Can you try to disable multi-processing by setting "--num_workers 0"? For all these attempts you may use a small train/validation/test percent for a quick validation, for example by setting "--train_percent 0.01 --val_percent 0.01 --test_percent 0.01".

**Comment by VeritasYin** [comment]
I was able to run the code with defacult setting on ogbl-citation2 once. But later, the code randomly stopped at the begining of certain epoch (attached). It was still runing based the status from htop but the process par was not moving.

`Run: 01, Epoch: 02, Loss: 0.0788, Valid: 88.97%, Test: 86.36%
  0%|                                       | 0/37985 [00:00<?, ?it/s]`

**Comment by muhanzhang** [comment]
If you "ctrl c" at the stuck point, what will be printed? I wonder where it is stuck at. Perhaps there are some dead loops.

**Comment by VeritasYin** [comment]
I got something like this

```
Traceback (most recent call last):
  File "seal_link_pred.py", line 651, in <module>
    loss = train()
  File "seal_link_pred.py", line 159, in train
    for data in pbar:
  File "~/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "~/anaconda3/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "~/anaconda3/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "~/anaconda3/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "~/anaconda3/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "~/anaconda3/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

**Comment by muhanzhang** [comment]
It seems to be related to multiprocessing. Can you try to disable multiprocessing by using "--num_workers 0"?
